automation:
  - alias: White Cube Enable Lights
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.white_cube_action
        to: 'slide'
      - platform: state
        entity_id: sensor.white_cube_action
        to: 'fall'
    action:
      - service: light.turn_on
        target:
          entity_id: light.bedside
  - alias: White Cube Enable disable light
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.white_cube_action
        to: 'shake'
    action:
      - service: light.turn_off
  - alias: White Cube Rotate
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.white_cube_action
        to: rotate_left
      - platform: state
        entity_id: sensor.white_cube_action
        to: rotate_right
    action:
      - service: light.turn_on
        entity_id: light.bedside_south
        data:
          brightness: >-
            {{ (state_attr('light.bedside_south', 'brightness') | int) +
            (trigger.to_state.attributes.angle | int) }}
      - service: light.turn_on
        entity_id: light.bedside_north
        data:
          brightness: >-
            {{ (state_attr('light.bedside_north', 'brightness') | int) +
            (trigger.to_state.attributes.angle | int) }}
        target:
          entity_id: light.bedside
  - alias: White Cube Side 1
    mode: single
    trigger:
      platform: state
      entity_id: sensor.white_cube_action_side
      to: '1'
    action:
      scene: scene.bedside_ftp
  - alias: White Cube Side 2
    mode: single
    trigger:
      platform: state
      entity_id: sensor.white_cube_action_side
      to: '2'
    action:
      scene: scene.bedside_rastafari
  - alias: White Cube Side 3
    mode: single
    trigger:
      platform: state
      entity_id: sensor.white_cube_action_side
      to: '3'
    action:
      scene: scene.bedside_night
  - alias: White Cube Side 4
    mode: single
    trigger:
      platform: state
      entity_id: sensor.white_cube_action_side
      to: '4'
    action:
      scene: scene.bedside_ukraine
  - alias: White Cube Side 5
    mode: single
    trigger:
      platform: state
      entity_id: sensor.white_cube_action_side
      to: '5'
    action:
      scene: scene.bedside_carrot
  - alias: White Cube Side 6
    mode: single
    trigger:
      platform: state
      entity_id: sensor.white_cube_action_side
      to: '6'
    action:
      scene: scene.bedside_peach
