- id: mba_connected
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.macbook_air_misha_displays
      to: '2'
      from: '1'
  action:
    service: light.turn_on
    target:
      entity_id:
        - light.desk
- id: mba_disconnected
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.macbook_air_misha_displays
      to: '1'
      from: '2'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.desk

- id: pink_cube_slide
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.pink_cube_action
      to: 'slide'
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.desk
- id: pink_cube_rotate
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.pink_cube_action
      to: 'rotate_left'
    - platform: state
      entity_id: sensor.pink_cube_action
      to: 'rotate_right'
  action:
    - service: light.turn_on
      entity_id: light.desk_backlight
      data:
        brightness: >-
          {{ (state_attr('light.desk_backlight', 'brightness') | int) +
          (trigger.to_state.attributes.angle | int) }}
    - service: light.turn_on
      entity_id: light.desk_lamp
      data:
        brightness: >-
          {{ (state_attr('light.desk_lamp', 'brightness') | int) +
          (trigger.to_state.attributes.angle | int) }}
- id: pink_cube_shake
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.pink_cube_action
      to: 'shake'
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.desk
- id: pink_cube_flip90
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.pink_cube_action
      to: 'flip90'
  action:
    service: input_select.select_next
    target:
      entity_id: input_select.desk_scenes
      

# Desk scenes
- id: "hulk-smash-selected"
  alias: Desk — Hulk smash selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: hulk-smash
  action:
    scene: scene.desk_hulk_smash
  mode: single
- id: "lava-selected"
  alias: Desk — Lava selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: lava
  action:
    scene: scene.desk_lava
  mode: single
- id: "icecold-selected"
  alias: Desk — Ice cold selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: icecold
  action:
    scene: scene.desk_ice_cold
  mode: single
- id: "carrot-selected"
  alias: Desk — Carrot selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: carrot
  action:
    scene: scene.desk_carrot
  mode: single
- id: "icefire-selected"
  alias: Desk — Ice fire selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: icefire
  action:
    scene: scene.desk_ice_fire
  mode: single
