# Cube events
- id: "cube-fall"
  alias: Cube — Fall
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00010ec987_action
        click_type: free_fall
  condition: []
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.desk
  mode: single
- id: "cube-move"
  alias: Cube — Move
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00010ec987_action
        click_type: move
  condition: []
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.desk
  mode: single
- id: "cube-flip90"
  alias: Cube — Flip 90
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00010ec987_action
        click_type: flip90
  condition: []
  action:
    service: input_select.select_next
    target:
      entity_id: input_select.desk_scenes
  mode: single
- id: "cube-shake"
  alias: Cube — Shake
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00010ec987_action
        click_type: shake_air
  condition: []
  action:
    scene: scene.bedroom_warm_white
  mode: single

# Desk scenes
- id: "hulk-smash-selected"
  alias: Desk — Hulk smash selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: hulk-smash
  action:
    scene: scene.desk_hulk_smash
  mode: single
- id: "lava-selected"
  alias: Desk — Lava selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: lava
  action:
    scene: scene.desk_lava
  mode: single
- id: "icecold-selected"
  alias: Desk — Ice cold selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: icecold
  action:
    scene: scene.desk_ice_cold
  mode: single
- id: "carrot-selected"
  alias: Desk — Carrot selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: carrot
  action:
    scene: scene.desk_carrot
  mode: single
- id: "icefire-selected"
  alias: Desk — Ice fire selected
  trigger:
    - platform: state
      entity_id: input_select.desk_scenes
      to: icefire
  action:
    scene: scene.desk_ice_fire
  mode: single
