# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

input_select:
  desk_scenes:
    name: Desk scenes
    options:
      - hulk-smash
      - lava
      - carrot
      - icecold
      - icefire

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
homeassistant:
  customize: !include customize.yaml
