light.bedside:
  icon: mdi:bed
  friendly_name: Спальня
light.bedside_north:
  icon: mdi:globe-light
  friendly_name: Спальня - Север
light.bedside_south:
  icon: mdi:globe-light
  friendly_name: Спальня - Юг
light.desk:
  icon: mdi:desk
  friendly_name: Стол
light.desk_backlight:
  icon: mdi:led-strip-variant
  friendly_name: Стол - Лента
light.desk_lamp:
  icon: mdi:desk-lamp
  friendly_name: Стол - Лампа
