- platform: flux_led
  devices:
    192.168.31.114:
      name: desk_lamp
      mode: 'rgb'
    192.168.31.200:
      name: bedside_south
      mode: 'rgb'
    192.168.31.53:
      name: bedside_north
      mode: 'rgb'

- platform: group
  name: bedside
  entities:
    - light.bedside_north
    - light.bedside_south
- platform: group
  name: desk
  entities:
    - light.desk_lamp
    - light.desk_backlight
