- id: 'hulk_smash'
  name: Desk — Hulk Smash
  entities:
    light.desk_backlight:
      brightness: 255
      rgb_color:
      - 191
      - 0
      - 255
      state: 'on'
    light.desk_lamp:
      brightness: 255
      rgb_color:
      - 0
      - 255
      - 21
      state: 'on'
  icon: mdi:radioactive
- id: 'lava'
  name: Desk — Lava
  entities:
    light.desk_backlight:
      brightness: 255
      rgb_color:
      - 255
      - 216
      - 0
      state: 'on'
    light.desk_lamp:
      brightness: 255
      rgb_color:
        - 255
        - 0
        - 20
      state: 'on'
  icon: mdi:fire
- id: 'carrot'
  name: Desk — Carrot
  entities:
    light.desk_backlight:
      brightness: 255
      rgb_color:
      - 255
      - 84
      - 0
      state: 'on'
    light.desk_lamp:
      brightness: 255
      rgb_color:
      - 255
      - 171
      - 32
      state: 'on'
  icon: mdi:carrot
- id: 'icecold'
  name: Desk — Ice Cold
  entities:
    light.desk_backlight:
      brightness: 255
      rgb_color:
      - 0
      - 29
      - 255
      state: 'on'
    light.desk_lamp:
      brightness: 255
      rgb_color:
      - 0
      - 151
      - 255
      state: 'on'
  icon: mdi:weather-snowy
- id: icefire
  name: Desk — Ice Fire
  entities:
    light.desk_backlight:
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 89
      state: 'on'
    light.desk_lamp:
      brightness: 255
      rgb_color:
      - 0
      - 0
      - 255
      state: 'on'
  icon: mdi:weather-snowy
