homeassistant:
  customize:
    light.bedside:
      icon: mdi:bed
      friendly_name: Спальня
    light.bedside_north:
      icon: mdi:globe-light
      friendly_name: Спальня - Север
    light.bedside_south:
      icon: mdi:globe-light
      friendly_name: Спальня - Юг