- id: '1619889351615'
  alias: Cube fall
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d00010ec987_action
      click_type: free_fall
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.chandelier
      - light.desk
  mode: single
