automation:
  - alias: MacBook Docked
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.macbook_air_misha_displays
        to: '2'
        from: '1'
    action:
      service: light.turn_on
      target:
        entity_id: light.desk
  - alias: MacBook Undocked
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.macbook_air_misha_displays
        to: '1'
        from: '2'
    action:
      service: light.turn_off
      target:
        entity_id: light.desk