light:
  - platform: flux_led
    devices:
      192.168.31.200:
        name: bedside_south
        mode: 'rgb'
      192.168.31.53:
        name: bedside_north
        mode: 'rgb'

  - platform: group
    name: bedside
    entities:
      - light.bedside_north
      - light.bedside_south

homeassistant:
  customize:
    light.bedside:
      icon: mdi:bed
      friendly_name: Спальня
    light.bedside_north:
      icon: mdi:globe-light
      friendly_name: Спальня - Север
    light.bedside_south:
      icon: mdi:globe-light
      friendly_name: Спальня - Юг

scene:
  - name: Bedside FTP
    entities:
      light.bedside_south:
        state: 'on'
        brightness: 165
        rgb_color:
        - 163
        - 0
        - 16
      light.bedside_north:
        state: 'on'
        brightness: 135
        rgb_color:
        - 0
        - 34
        - 132
  - name: Bedside Rastafari
    entities:
      light.bedside_south:
        state: 'on'
        brightness: 165
        rgb_color:
        - 163
        - 61
        - 0
      light.bedside_north:
        state: 'on'
        brightness: 165
        rgb_color:
        - 0
        - 132
        - 12
  - name: Bedside Night
    entities:
      light.bedside_south:
        state: 'on'
        brightness: 165
        rgb_color:
        - 52
        - 6
        - 0
      light.bedside_north:
        state: 'on'
        brightness: 165
        rgb_color:
        - 52
        - 6
        - 0
  - name: Bedside Ukraine
    entities:
      light.bedside_south:
        state: 'on'
        brightness: 165
        rgb_color:
        - 207
        - 125
        - 0
      light.bedside_north:  
        state: 'on'
        brightness: 165
        rgb_color:
        - 0
        - 87
        - 116
  - name: Bedside Carrot
    entities:
      light.bedside_south:
        state: 'on'
        brightness: 165
        rgb_color:
        - 0
        - 128
        - 14
      light.bedside_north:
        state: 'on'
        brightness: 165
        rgb_color:
        - 116
        - 21
        - 0
  - name: Bedside Peach
    entities:
      light.bedside_south:
        state: 'on'
        brightness: 165
        rgb_color:
          - 116
          - 20
          - 0
      light.bedside_north:
        state: 'on'
        brightness: 165
        rgb_color:
          - 128
          - 13
          - 13