---
light:
  - platform: desk_light
    entities:
      desk_strip: '192.168.31.22'
  - platform: group
    name: desk
    entities:
      - light.screen_bar_back
      - light.screen_bar_front
      - light.desk_strip

scene:
  - name: Desk Hulk Smash
    entities:
      light.desk_strip:
        brightness: 221
        rgb_color:
          - 0
          - 255
          - 16
        state: 'on'
      light.screen_bar_back:
        brightness: 255
        rgb_color:
          - 255
          - 0
          - 255
        state: 'on'
  - name: Desk Lava
    entities:
      light.desk_strip:
        brightness: 168
        rgb_color:
          - 255
          - 0
          - 29
        state: 'on'
      light.screen_bar_back:
        brightness: 255
        rgb_color:
          - 255
          - 172
          - 0
        state: 'on'
    icon: mdi:fire
  - name: Desk Carrot
    entities:
      light.desk_strip:
        brightness: 170
        rgb_color:
          - 255
          - 172
          - 145
        state: 'on'
      light.screen_bar_back:
        brightness: 255
        rgb_color:
          - 96
          - 255
          - 135
        state: 'on'
    icon: mdi:carrot
  - name: Desk Magentish
    entities:
      light.desk_strip:
        brightness: 175
        rgb_color:
          - 255
          - 0
          - 255
        state: 'on'
      light.screen_bar_back:
        brightness: 255
        rgb_color:
          - 255
          - 168
          - 0
        state: 'on'
    icon: mdi:flower
  - name: Desk Ice Fire
    entities:
      light.desk_strip:
        brightness: 200
        rgb_color:
          - 0
          - 63
          - 255
        state: 'on'
      light.screen_bar_back:
        brightness: 255
        rgb_color:
          - 255
          - 0
          - 64
        state: 'on'
  - name: Desk Neon
    entities:
      light.desk_strip:
        brightness: 255
        rgb_color:
          - 0
          - 0
          - 255
        state: 'on'
      light.screen_bar_back:
        brightness: 255
        rgb_color:
          - 0
          - 255
          - 45
        state: 'on'

input_select:
  living_room_scene:
    name: Living Room scene
    icon: mdi:sofa-outline
    options:
      - desk_hulk_smash
      - desk_lava
      - desk_carrot
      - desk_magentish
      - desk_ice_fire
      - desk_neon

automation:
  - alias: Living Room scene selector
    trigger:
      platform: state
      entity_id: input_select.living_room_scene
    action:
      service: scene.turn_on
      data_template:
        entity_id: scene.{{trigger.to_state.state}}

homeassistant:
  customize:
    light.desk:
      icon: mdi:desk
      friendly_name: Стол
    light.desk_strip:
      icon: mdi:led-strip-variant
      friendly_name: Стол - Нижняя подсветка
    light.screen_bar_back:
      icon: mdi:television-ambient-light
      friendly_name: Стол - Верх экрана
    light.screen_bar_front:
      icon: mdi:texture-box
      friendly_name: Стол - Рабочая поверхность
